apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 383944855594.dkr.ecr.ap-northeast-3.amazonaws.com/myapp-repo-0624
  newName: 383944855594.dkr.ecr.ap-northeast-3.amazonaws.com/myapp-repo-0624
  newTag: 1765925e
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
