---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-nodejs-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-nodejs-backend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30
