---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 383944855594.dkr.ecr.ap-northeast-3.amazonaws.com/myapp-repo-0624:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
